name: Test Backend Service
on: [push, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    env:
      working-directory: ${{github.workspace}}/kanban-board-service
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev

      - name: Install Python dependencies
        working-directory: ${{env.working-directory}}
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: Build
        run: |
          cmake -S ${{github.workspace}}/kanban-board-service -B ${{github.workspace}}/kanban-board-service/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/kanban-board-service/build --config ${{env.BUILD_TYPE}}

      - name: Start the service
        working-directory: ${{env.working-directory}}/build
        run: |
          ./Service &> service.log &

      - name: Excute Pytest script 🍏
        working-directory: ${{env.working-directory}}
        run: |
          pytest -v -s

      - name: Print Service Output
        if: always()
        run: cat ${{github.workspace}}/kanban-board-service/build/service.log
